name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: kanti/buildy step
        uses: docker://kanti/buildy:7.2
      - run: composer install --no-progress --no-scripts -n
      - run: ./vendor/bin/grumphp run