name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baschny/php-composer-action@v1
        with:
          composer_version: 2
          command: install
          args: --no-progress --no-scripts -n
      - run: ./vendor/bin/grumphp run