name: Run grumphp with different versions
on: [push]
jobs:
  php_72:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['72', '74']
        composer:
          - install --no-progress --no-scripts -n
          - update --no-progress --no-scripts -n --prefer-lowest
          - require phpro/grumphp:* --no-progress --no-scripts -n
    steps:
      - uses: actions/checkout@v2
      - name: kanti/buildy step
        uses: ./.github/actions/buildy-action
        with:
          phpversion: ${{ matrix.php }}
      - run: composer ${{ matrix.composer }}
      - run: ./vendor/bin/grumphp run
