name: Run grumphp with different versions
on: [push]
jobs:
  php_72:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [docker://kanti/buildy:7.2, docker://kanti/buildy:7.3, docker://kanti/buildy:7.4, docker://kanti/buildy:8.0]
        composer:
          - install --no-progress --no-scripts -n
          - update --no-progress --no-scripts -n --prefer-lowest
          - require phpro/grumphp:* --no-progress --no-scripts -n
    steps:
      - uses: actions/checkout@v2
      - name: kanti/buildy step
        uses: ${{ matrix.php }}
      - run: composer ${{ matrix.composer }}
      - run: ./vendor/bin/grumphp run
